apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-matchmakingserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}-matchmakingserver
  replicas: {{ default 1 .Values.mailserver.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}-matchmakingserver
    spec:
      containers:
      - name: {{ .Release.Name }}-matchmakingserver
        image: "{{ .Values.matchmakingserver.image.repository }}:{{ .Values.matchmakingserver.image.tag }}"
        imagePullPolicy: {{ .Values.mailserver.image.pullPolicy | toString }}
        env:
        - name: PORT
          value: "{{ .Values.matchmakingserver.service.internalPort | int }}"
        - name: NATS_URL
          value: nats://{{ .Release.Name }}-nats:4222
        - name: SERVERS_REGISTRY_SERVICE_ADDRESS
          value: {{ .Release.Name }}-servers-registry:{{ .Values.servers_registry.service.externalPort}}
        - name: CHAR_DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-databases-config
              key: CHAR_DB_CONNECTION
        - name: WORLD_DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-databases-config
              key: WORLD_DB_CONNECTION
        ports:
        - containerPort: {{ .Values.matchmakingserver.service.internalPort | int  }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.matchmakingserver.service.internalPort | int }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.matchmakingserver.service.internalPort | int }}
        securityContext:
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
          # runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
{{ toYaml .Values.resources | indent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matchmakingserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.mailserver.service.type }}
  ports:
  - port: {{ .Values.matchmakingserver.service.externalPort | int  }}
    targetPort: {{ .Values.matchmakingserver.service.internalPort | int  }}
    protocol: TCP
  selector:
    app: {{ $fullname }}-matchmakingserver