name: Build and Push Gameserver Images

on:
  workflow_dispatch:

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and push AzerothCore gameserver image (AMD64)'
        run: |
          docker buildx build --push --platform linux/amd64 -t ghcr.io/${{github.actor}}/gameserver-ac:${{github.ref_name}} -f game-server/azerothcore/Dockerfile .

  build-and-push-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and push AzerothCore gameserver image (ARM64)'
        run: |
          docker buildx build --push --platform linux/arm64 -t ghcr.io/${{github.actor}}/gameserver-ac:${{github.ref_name}} -f game-server/azerothcore/Dockerfile .
