name: Build and Push Go Images

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push "authserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/authserver:${{github.ref_name}} -f apps/authserver/Dockerfile . 

      - name: 'Build and push "charserver" image'
        run: |          
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/charserver:${{github.ref_name}} -f apps/charserver/Dockerfile . 

      - name: 'Build and push "chatserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/chatserver:${{github.ref_name}} -f apps/chatserver/Dockerfile . 

      - name: 'Build and push "game-load-balancer" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/game-load-balancer:${{github.ref_name}} -f apps/game-load-balancer/Dockerfile . 

      - name: 'Build and push "guidserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/guidserver:${{github.ref_name}} -f apps/guidserver/Dockerfile . 

      - name: 'Build and push "guildserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/guildserver:${{github.ref_name}} -f apps/guildserver/Dockerfile . 

      - name: 'Build and push "mailserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/mailserver:${{github.ref_name}} -f apps/mailserver/Dockerfile . 

      - name: 'Build and push "groupserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/groupserver:${{github.ref_name}} -f apps/groupserver/Dockerfile . 

      - name: 'Build and push "matchmakingserver" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/matchmakingserver:${{github.ref_name}} -f apps/matchmakingserver/Dockerfile . 

      - name: 'Build and push "mysqlreverseproxy" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/mysqlreverseproxy:${{github.ref_name}} -f apps/mysqlreverseproxy/Dockerfile . 

      - name: 'Build and push "servers-registry" image'
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{github.actor}}/servers-registry:${{github.ref_name}} -f apps/servers-registry/Dockerfile . 
